apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  generation: 1
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-Ingress
  namespace: default
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}-Service
          servicePort: 80
        path: /
